### ISSUE TITLE
Розібратися з роботою eлементу Spinner

### ISSUE THREAD

**Issue by Koiji** [flame4ost/SmilaTrainBus#1]
- [x] Продивитися теоретичний матеріал

- [x] Використати набуті знання на практиці

**Comment by gavrikman** [comment]
Watch this video!
https://www.youtube.com/watch?v=on_OrrX7Nw4

**Comment by gzaspa** [comment]
Потрібно в Assignees вказати себе. Також вказати Milestone і Estimate.
